export enum ActivityType {
  NEW_USER = "NEW_USER",
  PURCHASE_CREDITS_INITIATED = "PURCHASE_CREDITS_INITIATED",
  GRANT_REVIEW_CREDITS = "GRANT_REVIEW_CREDITS",
  PURCHASE_CREDITS = "PURCHASE_CREDITS",
  USE_CREDITS = "USE_CREDITS",
}
